name: Test Suite

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      matrix:
        elixir: ['1.8', '1.9', '1.10', '1.11']

    runs-on: ubuntu-latest
    container:
      image: elixir:${{ matrix.elixir }}-alpine
      env:
        MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk upgrade
          apk add git cargo=1.47.0-r1

      - name: Setup Deps Cache
        uses: actions/cache@v1
        with:
          path: deps
          key: v1-deps-${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            v1-deps-${{ runner.os }}-

      - name: Setup Build Cache
        uses: actions/cache@v1
        with:
          path: _build
          key: v1-build-${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            v1-build-${{ runner.os }}-

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mix test
